In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%precision 3
%matplotlib inline

In [10]:
df = pd.read_csv('/Users/hwon/Desktop/통계적 분석 과제/data/ch4_scores400.csv')
scores = np.array(df['score'])
scores[:10]

array([76, 55, 80, 80, 74, 61, 81, 76, 23, 80])

In [6]:
np.random.choice([1,2,3],3)

array([3, 3, 1])

In [7]:
np.random.choice([1,2,3],3,replace=False)

array([1, 2, 3])

In [11]:
np.random.seed(0)
np.random.choice([1,2,3],3)

array([2, 1, 1])

In [12]:
np.random.seed(0)
sample = np.random.choice(scores, 20)

sample.mean()

70.400

In [15]:
scores.mean()

69.530

In [6]:
for i in range(5):
    sample = np.random.choice(scores, 20)
    print(f'{i+1}번째 무작위 추출로 얻은 표본평균' , sample.mean())

1번째 무작위 추출로 얻은 표본평균 72.65
2번째 무작위 추출로 얻은 표본평균 76.45
3번째 무작위 추출로 얻은 표본평균 68.9
4번째 무작위 추출로 얻은 표본평균 67.45
5번째 무작위 추출로 얻은 표본평균 74.5


In [7]:
dice = [1, 2, 3, 4, 5, 6]
prob = [1/21, 2/21, 3/21, 4/21, 5/21, 6/21]

In [8]:
np.random.choice(dice, p=prob)

np.int64(2)